# Generated by Django 2.2.16 on 2022-05-04 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220504_1957'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_me_is_reserved',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]{1,150}$', message='Не более 150 символов, допустимы только буквы, цифры и @/./+/-/_'), django.core.validators.RegexValidator('^me$', inverse_match=True, message='Имя пользователя me не может быть использовано')], verbose_name='Имя пользователя'),
        ),
    ]
