# Generated by Django 2.2.16 on 2022-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220427_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
