# Generated by Django 2.2.16 on 2022-05-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220505_0235'),
        ('reviews', '0003_auto_20220504_1914'),
        ('reviews', '0003_auto_20220504_1044'),
    ]

    operations = [
    ]
