# Generated by Django 2.2.16 on 2022-04-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_user_confirmation_code'),
        ('reviews', '0006_auto_20220428_2302'),
    ]

    operations = [
    ]
