# Generated by Django 2.2.16 on 2022-04-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_merge_20220429_1114'),
        ('reviews', '0007_merge_20220429_1359'),
    ]

    operations = [
    ]
