# Generated by Django 2.2.16 on 2022-04-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220429_1851'),
        ('reviews', '0009_auto_20220429_1543'),
    ]

    operations = [
    ]
