# Generated by Django 2.2.16 on 2022-04-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_merge_20220429_1911'),
        ('reviews', '0010_merge_20220429_2341'),
    ]

    operations = [
    ]
