# Generated by Django 2.2.16 on 2022-04-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_merge_20220429_2341'),
        ('reviews', '0010_merge_20220429_1904'),
    ]

    operations = [
    ]
